export const countries = [
  { value: 'Afghanistan', label: 'Afghanistan' },
  { value: 'Albania', label: 'Albania' },
  { value: 'Algeria', label: 'Algeria' },
  { value: 'Andorra', label: 'Andorra' },
  { value: 'Angola', label: 'Angola' },
  { value: 'Antigua and Barbuda', label: 'Antigua and Barbuda' },
  { value: 'Argentina', label: 'Argentina' },
  { value: 'Armenia', label: 'Armenia' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan' },
  { value: 'Bahamas', label: 'Bahamas' },
  { value: 'Bahrain', label: 'Bahrain' },
  { value: 'Bangladesh', label: 'Bangladesh' },
  { value: 'Barbados', label: 'Barbados' },
  { value: 'Belarus', label: 'Belarus' },
  { value: 'Belgium', label: 'Belgium' },
  { value: 'Belize', label: 'Belize' },
  { value: 'Benin', label: 'Benin' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Bolivia', label: 'Bolivia' },
  { value: 'Bosnia and Herzegovina', label: 'Bosnia and Herzegovina' },
  { value: 'Botswana', label: 'Botswana' },
  { value: 'Brazil', label: 'Brazil' },
  { value: 'Brunei', label: 'Brunei' },
  { value: 'Bulgaria', label: 'Bulgaria' },
  { value: 'Burkina Faso', label: 'Burkina Faso' },
  { value: 'Burundi', label: 'Burundi' },
  { value: 'Cabo Verde', label: 'Cabo Verde' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Cameroon', label: 'Cameroon' },
  { value: 'Canada', label: 'Canada' },
  { value: 'Central African Republic', label: 'Central African Republic' },
  { value: 'Chad', label: 'Chad' },
  { value: 'Chile', label: 'Chile' },
  { value: 'China', label: 'China' },
  { value: 'Colombia', label: 'Colombia' },
  { value: 'Comoros', label: 'Comoros' },
  { value: 'Congo (Brazzaville)', label: 'Congo (Brazzaville)' },
  { value: 'Congo (Kinshasa)', label: 'Congo (Kinshasa)' },
  { value: 'Costa Rica', label: 'Costa Rica' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Cuba', label: 'Cuba' },
  { value: 'Cyprus', label: 'Cyprus' },
  { value: 'Czechia', label: 'Czechia' },
  { value: 'Denmark', label: 'Denmark' },
  { value: 'Djibouti', label: 'Djibouti' },
  { value: 'Dominica', label: 'Dominica' },
  { value: 'Dominican Republic', label: 'Dominican Republic' },
  { value: 'East Timor', label: 'East Timor' },
  { value: 'Ecuador', label: 'Ecuador' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'El Salvador', label: 'El Salvador' },
  { value: 'Equatorial Guinea', label: 'Equatorial Guinea' },
  { value: 'Eritrea', label: 'Eritrea' },
  { value: 'Estonia', label: 'Estonia' },
  { value: 'Eswatini', label: 'Eswatini' },
  { value: 'Ethiopia', label: 'Ethiopia' },
  { value: 'Fiji', label: 'Fiji' },
  { value: 'Finland', label: 'Finland' },
  { value: 'France', label: 'France' },
  { value: 'Gabon', label: 'Gabon' },
  { value: 'Gambia', label: 'Gambia' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Ghana', label: 'Ghana' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Grenada', label: 'Grenada' },
  { value: 'Guatemala', label: 'Guatemala' },
  { value: 'Guinea', label: 'Guinea' },
  { value: 'Guinea-Bissau', label: 'Guinea-Bissau' },
  { value: 'Guyana', label: 'Guyana' },
  { value: 'Haiti', label: 'Haiti' },
  { value: 'Honduras', label: 'Honduras' },
  { value: 'Hungary', label: 'Hungary' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'India', label: 'India' },
  { value: 'Indonesia', label: 'Indonesia' },
  { value: 'Iran', label: 'Iran' },
  { value: 'Iraq', label: 'Iraq' },
  { value: 'Ireland', label: 'Ireland' },
  { value: 'Israel', label: 'Israel' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Ivory Coast', label: 'Ivory Coast' },
  { value: 'Jamaica', label: 'Jamaica' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kazakhstan', label: 'Kazakhstan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'Kiribati', label: 'Kiribati' },
  { value: 'Kosovo', label: 'Kosovo' },
  { value: 'Kuwait', label: 'Kuwait' },
  { value: 'Kyrgyzstan', label: 'Kyrgyzstan' },
  { value: 'Laos', label: 'Laos' },
  { value: 'Latvia', label: 'Latvia' },
  { value: 'Lebanon', label: 'Lebanon' },
  { value: 'Lesotho', label: 'Lesotho' },
  { value: 'Liberia', label: 'Liberia' },
  { value: 'Libya', label: 'Libya' },
  { value: 'Liechtenstein', label: 'Liechtenstein' },
  { value: 'Lithuania', label: 'Lithuania' },
  { value: 'Luxembourg', label: 'Luxembourg' },
  { value: 'Madagascar', label: 'Madagascar' },
  { value: 'Malawi', label: 'Malawi' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mali', label: 'Mali' },
  { value: 'Malta', label: 'Malta' },
  { value: 'Marshall Islands', label: 'Marshall Islands' },
  { value: 'Mauritania', label: 'Mauritania' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Mexico', label: 'Mexico' },
  { value: 'Micronesia', label: 'Micronesia' },
  { value: 'Moldova', label: 'Moldova' },
  { value: 'Monaco', label: 'Monaco' },
  { value: 'Mongolia', label: 'Mongolia' },
  { value: 'Montenegro', label: 'Montenegro' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Mozambique', label: 'Mozambique' },
  { value: 'Myanmar', label: 'Myanmar' },
  { value: 'Namibia', label: 'Namibia' },
  { value: 'Nauru', label: 'Nauru' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'Netherlands', label: 'Netherlands' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Nicaragua', label: 'Nicaragua' },
  { value: 'Niger', label: 'Niger' },
  { value: 'Nigeria', label: 'Nigeria' },
  { value: 'North Macedonia', label: 'North Macedonia' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Oman', label: 'Oman' },
  { value: 'Pakistan', label: 'Pakistan' },
  { value: 'Palau', label: 'Palau' },
  { value: 'Palestine', label: 'Palestine' },
  { value: 'Panama', label: 'Panama' },
  { value: 'Papua New Guinea', label: 'Papua New Guinea' },
  { value: 'Paraguay', label: 'Paraguay' },
  { value: 'Peru', label: 'Peru' },
  { value: 'Philippines', label: 'Philippines' },
  { value: 'Poland', label: 'Poland' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Qatar', label: 'Qatar' },
  { value: 'Romania', label: 'Romania' },
  { value: 'Russia', label: 'Russia' },
  { value: 'Rwanda', label: 'Rwanda' },
  { value: 'Saint Kitts and Nevis', label: 'Saint Kitts and Nevis' },
  { value: 'Saint Lucia', label: 'Saint Lucia' },
  {
    value: 'Saint Vincent and the Grenadines',
    label: 'Saint Vincent and the Grenadines',
  },
  { value: 'Samoa', label: 'Samoa' },
  { value: 'San Marino', label: 'San Marino' },
  { value: 'Sao Tome and Principe', label: 'Sao Tome and Principe' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Senegal', label: 'Senegal' },
  { value: 'Serbia', label: 'Serbia' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Sierra Leone', label: 'Sierra Leone' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Slovakia', label: 'Slovakia' },
  { value: 'Slovenia', label: 'Slovenia' },
  { value: 'Solomon Islands', label: 'Solomon Islands' },
  { value: 'Somalia', label: 'Somalia' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Korea', label: 'South Korea' },
  { value: 'South Sudan', label: 'South Sudan' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Sudan', label: 'Sudan' },
  { value: 'Suriname', label: 'Suriname' },
  { value: 'Sweden', label: 'Sweden' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Syria', label: 'Syria' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tajikistan', label: 'Tajikistan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Togo', label: 'Togo' },
  { value: 'Tonga', label: 'Tonga' },
  { value: 'Trinidad and Tobago', label: 'Trinidad and Tobago' },
  { value: 'Tunisia', label: 'Tunisia' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'Turkmenistan', label: 'Turkmenistan' },
  { value: 'Tuvalu', label: 'Tuvalu' },
  { value: 'Uganda', label: 'Uganda' },
  { value: 'Ukraine', label: 'Ukraine' },
  { value: 'United Arab Emirates', label: 'United Arab Emirates' },
  { value: 'United Kingdom', label: 'United Kingdom' },
  { value: 'United States', label: 'United States' },
  { value: 'Uruguay', label: 'Uruguay' },
  { value: 'Uzbekistan', label: 'Uzbekistan' },
  { value: 'Vanuatu', label: 'Vanuatu' },
  { value: 'Vatican City', label: 'Vatican City' },
  { value: 'Venezuela', label: 'Venezuela' },
  { value: 'Vietnam', label: 'Vietnam' },
  { value: 'Yemen', label: 'Yemen' },
  { value: 'Zambia', label: 'Zambia' },
  { value: 'Zimbabwe', label: 'Zimbabwe' },
];

export const departments = [
  { value: 'Education', label: 'Education' },
  { value: 'Agriculture', label: 'Agriculture' },
  { value: 'ICT', label: 'ICT' },
  { value: 'Manufacture', label: 'Manufacture' },
  { value: 'Research', label: 'Research' },
  { value: 'Creative Economy', label: 'Creative Economy' },
  { value: 'Entertainment', label: 'Entertainment' },
  { value: 'Sports Development', label: 'Sports Development' },
  { value: 'Transportation', label: 'Transportation' },
  { value: 'Housing', label: 'Housing' },
  { value: 'Urban Plan', label: 'Urban Plan' },
  { value: 'Media', label: 'Media' },
  { value: 'Healthcare', label: 'Healthcare' },
  { value: 'Mining', label: 'Mining' },
  { value: 'Tourism', label: 'Tourism' },
];

export const states = [
  {
    value: 'Abia State',
    label: 'Abia State',
    lga: [
      { value: 'Aba North', label: 'Aba North' },
      { value: 'Aba South', label: 'Aba South' },
      { value: 'Arochukwu', label: 'Arochukwu' },
      { value: 'Bende', label: 'Bende' },
      { value: 'Ikwuano', label: 'Ikwuano' },
      { value: 'Isiala Ngwa North', label: 'Isiala Ngwa North' },
      { value: 'Isiala Ngwa South', label: 'Isiala Ngwa South' },
      { value: 'Isuikwuato', label: 'Isuikwuato' },
      { value: 'Obi Ngwa', label: 'Obi Ngwa' },
      { value: 'Ohafia', label: 'Ohafia' },
      { value: 'Osisioma Ngwa', label: 'Osisioma Ngwa' },
      { value: 'Ugwunagbo', label: 'Ugwunagbo' },
      { value: 'Ukwa East', label: 'Ukwa East' },
      { value: 'Ukwa West', label: 'Ukwa West' },
      { value: 'Umuahia North', label: 'Umuahia North' },
      { value: 'Umuahia South', label: 'Umuahia South' },
      { value: 'Umu Nneochi', label: 'Umu Nneochi' },
    ],
  },
  {
    value: 'Anambra State',
    label: 'Anambra State',
    lga: [
      { value: 'Aguata', label: 'Aguata' },
      { value: 'Anambra East', label: 'Anambra East' },
      { value: 'Anambra West', label: 'Anambra West' },
      { value: 'Anaocha', label: 'Anaocha' },
      { value: 'Awka North', label: 'Awka North' },
      { value: 'Awka South', label: 'Awka South' },
      { value: 'Ayamelum', label: 'Ayamelum' },
      { value: 'Dunukofia', label: 'Dunukofia' },
      { value: 'Ekwusigo', label: 'Ekwusigo' },
      { value: 'Idemili North', label: 'Idemili North' },
      { value: 'Idemili South', label: 'Idemili South' },
      { value: 'Ihiala', label: 'Ihiala' },
      { value: 'Njikoka', label: 'Njikoka' },
      { value: 'Nnewi North', label: 'Nnewi North' },
      { value: 'Nnewi South', label: 'Nnewi South' },
      { value: 'Ogbaru', label: 'Ogbaru' },
      { value: 'Onitsha North', label: 'Onitsha North' },
      { value: 'Onitsha South', label: 'Onitsha South' },
      { value: 'Orumba North', label: 'Orumba North' },
      { value: 'Orumba South', label: 'Orumba South' },
      { value: 'Oyi', label: 'Oyi' },
    ],
  },
  {
    value: 'Ebonyi State',
    label: 'Ebonyi State',
    lga: [
      { value: 'Abakaliki', label: 'Abakaliki' },
      { value: 'Afikpo North', label: 'Afikpo North' },
      { value: 'Afikpo South', label: 'Afikpo South' },
      { value: 'Ebonyi', label: 'Ebonyi' },
      { value: 'Ezza North', label: 'Ezza North' },
      { value: 'Ezza South', label: 'Ezza South' },
      { value: 'Ikwo', label: 'Ikwo' },
      { value: 'Ishielu', label: 'Ishielu' },
      { value: 'Ivo', label: 'Ivo' },
      { value: 'Izzi', label: 'Izzi' },
      { value: 'Ohaozara', label: 'Ohaozara' },
      { value: 'Ohaukwu', label: 'Ohaukwu' },
      { value: 'Onicha', label: 'Onicha' },
    ],
  },
  {
    value: 'Enugu State',
    label: 'Enugu State',
    lga: [
      { value: 'Aninri', label: 'Aninri' },
      { value: 'Awgu', label: 'Awgu' },
      { value: 'Enugu East', label: 'Enugu East' },
      { value: 'Enugu North', label: 'Enugu North' },
      { value: 'Enugu South', label: 'Enugu South' },
      { value: 'Ezeagu', label: 'Ezeagu' },
      { value: 'Igbo Etiti', label: 'Igbo Etiti' },
      { value: 'Igbo Eze North', label: 'Igbo Eze North' },
      { value: 'Igbo Eze South', label: 'Igbo Eze South' },
      { value: 'Isi Uzo', label: 'Isi Uzo' },
      { value: 'Nkanu East', label: 'Nkanu East' },
      { value: 'Nkanu West', label: 'Nkanu West' },
      { value: 'Nsukka', label: 'Nsukka' },
      { value: 'Oji River', label: 'Oji River' },
      { value: 'Udenu', label: 'Udenu' },
      { value: 'Udi', label: 'Udi' },
      { value: 'Uzo Uwani', label: 'Uzo Uwani' },
    ],
  },
  {
    value: 'Imo State',
    label: 'Imo State',
    lga: [
      { value: 'Aboh-Mbaise', label: 'Aboh-Mbaise' },
      { value: 'Ahiazu-Mbaise', label: 'Ahiazu-Mbaise' },
      { value: 'Ehime-Mbano', label: 'Ehime-Mbano' },
      { value: 'Ezinihitte', label: 'Ezinihitte' },
      { value: 'Ideato North', label: 'Ideato North' },
      { value: 'Ideato South', label: 'Ideato South' },
      { value: 'Ihitte/Uboma', label: 'Ihitte/Uboma' },
      { value: 'Ikeduru', label: 'Ikeduru' },
      { value: 'Isiala Mbano', label: 'Isiala Mbano' },
      { value: 'Isu', label: 'Isu' },
      { value: 'Mbaitoli', label: 'Mbaitoli' },
      { value: 'Ngor-Okpala', label: 'Ngor-Okpala' },
      { value: 'Njaba', label: 'Njaba' },
      { value: 'Nkwerre', label: 'Nkwerre' },
      { value: 'Nwangele', label: 'Nwangele' },
      { value: 'Obowo', label: 'Obowo' },
      { value: 'Oguta', label: 'Oguta' },
      { value: 'Ohaji/Egbema', label: 'Ohaji/Egbema' },
      { value: 'Okigwe', label: 'Okigwe' },
      { value: 'Orlu', label: 'Orlu' },
      { value: 'Orsu', label: 'Orsu' },
      { value: 'Oru East', label: 'Oru East' },
      { value: 'Oru West', label: 'Oru West' },
      { value: 'Owerri Municipal', label: 'Owerri Municipal' },
      { value: 'Owerri North', label: 'Owerri North' },
      { value: 'Owerri West', label: 'Owerri West' },
    ],
  },
  // Add more states and local government areas as needed
];
